os: linux
sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - nightly
  - pypy3

env:
  matrix:
    - DJANGO="<1.5"
    - DJANGO="<1.6"
    - DJANGO="<1.6" LOCALFLAVOR=django-localflavor
    - DJANGO="<1.7"
    - DJANGO="<1.7" LOCALFLAVOR=django-localflavor

install:
  - pip install Django$DJANGO $LOCALFLAVOR black
  - pip install .
  - pip install -r tests/requirements.txt

script:
  - coverage run tests/runtests.py --with-pep8 --force-all
  - black --check .

after_success:
  - pip install coveralls
  - coveralls

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
