language: python

python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.8
  - DJANGO=Django==1.5.4

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.3.7
    - python: 3.3
      env: DJANGO=Django==1.4.8

# command to install dependencies
install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install . --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"

# command to run tests
script: coverage run --source=wtforms_django tests/tests.py
after_success:
  - coveralls
