os: linux
sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - nightly
  - pypy3

env:
  - DJANGO="<1.12"
  - DJANGO="<2.1"
  - DJANGO="master"
matrix:
  exclude:
    - env: DJANGO="<2.1"
      python: 2.7
    - env: DJANGO="master"
      python: 3.4
  allow_failures:
    - python: nightly
    - env: DJANGO="master"

install:
  - pip install Django$DJANGO
  - pip install -r tests/requirements.txt

script:
  - coverage run tests/runtests.py --force-all

after_success:
  - pip install coveralls
  - coveralls

cache:
  - pip

branches:
  only:
    - master
    - test
    - /^.*-maintenance$/

notifications:
  email: false
