language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  global:
    - LOCALFLAVOR=
    - WTFORMS="<2.1"
  matrix:
    - DJANGO="<1.5"
    - DJANGO="<1.6"
    - DJANGO="<1.6" LOCALFLAVOR=django-localflavor
    - DJANGO="<1.6" WTFORMS="==1.0.5"
    - DJANGO="<1.6" WTFORMS="==1.0.5" LOCALFLAVOR=django-localflavor
    - DJANGO="<1.7" LOCALFLAVOR=django-localflavor
    - DJANGO="<1.7" WTFORMS="==1.0.5" LOCALFLAVOR=django-localflavor

matrix:
  exclude:
    - python: 3.3
      env: DJANGO="<1.5"

# command to install dependencies
install:
  - "pip install WTForms$WTFORMS Django$DJANGO $LOCALFLAVOR --use-mirrors"
  - "pip install . --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"

# command to run tests
script: coverage run --source=wtforms_django setup.py test
after_success:
  - coveralls
